# Changes here will be overwritten by Copier
_commit: 8c06bd5
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
email: dev@1kbgz.com
github: 1kbgz
project_description: Alias for csp-adapter-slack
project_name: csp-slack
python_version_primary: '3.11'
team: the csp-slack authors
