# Changes here will be overwritten by Copier
_commit: 42057e0
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: t.paine154@gmail.com
github: timkpaine
project_description: Alias for csp-adapter-slack
project_name: csp-slack
python_version_primary: '3.11'
team: the csp-slack authors
